name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: 'stable'

      - name: Build
        run: make ci

      - name: Upload coverage
        uses: actions/upload-artifact@v5
        with:
          name: coverage-${{ matrix.os }}
          path: coverage.*

      - run: go tool goreleaser release --clean --snapshot
        if: ${{ runner.os == 'Linux' }}

      - name: Upload dist
        uses: actions/upload-artifact@v5
        with:
          name: dist-${{ matrix.os }}
          path: dist
